name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux-llvm:
    runs-on: ubuntu-latest
    env:
      TARGET: linux,llvm
    steps:
      - uses: actions/checkout@v3

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: |
            build
          key: linux-build-${{ hashFiles('CMakeLists.txt', 'src/**') }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential llvm clang cmake python3-pip

      - name: Build zpiler
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j

      - name: Run Tests
        run: python3 test_runner.py

  test-windows:
    runs-on: windows-latest
    env:
      TARGET: windows
    steps:
      - uses: actions/checkout@v3

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: |
            build
          key: windows-build-${{ hashFiles('CMakeLists.txt', 'src/**') }}

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        run: choco install --no-progress -y cmake

      - name: Build zpiler
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=Debug
          nmake

      - name: Run Tests
        shell: cmd
        run: |
          chcp 65001
          python test_runner.py
